### ISSUE TITLE
Unhealthy maildev container in docker compose

### ISSUE THREAD

**Issue by Nikola-Milovic** [maildev/maildev#484] opened 2024-03-21 08:50 UTC
```
➜  docker ps | grep mail
7a82025c0d2e   maildev/maildev       "bin/maildev"            4 minutes ago    Up 4 minutes (unhealthy)   1025/tcp, 1080/tcp    maildev-1

➜ docker compose logs -f maildev
maildev-1  | MailDev using directory /tmp/maildev-1
maildev-1  | MailDev webapp running at http://0.0.0.0:1080/
maildev-1  | MailDev SMTP Server running at 0.0.0.0:1025
```

My docker compose file

```
  maildev:
    image: maildev/maildev:2.1.0
    networks:
      - platform
```

`Docker Compose version v2.25.0`

My maildev stopped being tracked by traefik since I updated docker compose, so it might be related not sure. A bit of debugging and I found that the container is unhealthy. Considering how barebones my setup is, I am guessing its something related to maildev itself

```
{
  "Status": "unhealthy",
  "FailingStreak": 5,
  "Log": [
    {
      "Start": "2024-03-21T09:52:10.217941825+01:00",
      "End": "2024-03-21T09:52:10.295743634+01:00",
      "ExitCode": 1,
      "Output": "Connecting to localhost:1080 ([::1]:1080)\nwget: can't connect to remote host: Connection refused\n"
    },
    {
      "Start": "2024-03-21T09:52:20.297273607+01:00",
      "End": "2024-03-21T09:52:20.37955279+01:00",
      "ExitCode": 1,
      "Output": "Connecting to localhost:1080 ([::1]:1080)\nwget: can't connect to remote host: Connection refused\n"
    },
    {
      "Start": "2024-03-21T09:52:30.380291256+01:00",
      "End": "2024-03-21T09:52:30.458289518+01:00",
      "ExitCode": 1,
      "Output": "Connecting to localhost:1080 ([::1]:1080)\nwget: can't connect to remote host: Connection refused\n"
    },
    {
      "Start": "2024-03-21T09:52:40.458959601+01:00",
      "End": "2024-03-21T09:52:40.563597174+01:00",
      "ExitCode": 1,
      "Output": "Connecting to localhost:1080 ([::1]:1080)\nwget: can't connect to remote host: Connection refused\n"
    },
    {
      "Start": "2024-03-21T09:52:50.564735793+01:00",
      "End": "2024-03-21T09:52:50.628254729+01:00",
      "ExitCode": 1,
      "Output": "Connecting to localhost:1080 ([::1]:1080)\nwget: can't connect to remote host: Connection refused\n"
    }
  ]
}
```

Can someone try and confirm that its working or not working for them as well?

**Comment by pallost** [comment] 2024-03-21 09:32
Same issue here. It works for me locally (MacOS) and appears healthy. At CI though I receive the same "MailDev SMTP Server running at 0.0.0.0:1025" success message, but the container still shows as unhealthy. Can it be something related to changes in docker daemon or something like that? Also, maildev/maildev image hasn't changed in 8 months apparently

**Comment by Nikola-Milovic** [comment] 2024-03-21 16:47
@pallost Seems that its docker related, my services are also having weird dns issues, and they cannot resolve any address

**Comment by pallost** [comment] 2024-03-22 05:53
For us:
- maildev container works locally in docker compose (both arm64 and amd64 images)
- maildev container does not work in gitlab CI in docker compose (it logs that the UI would have started but its own health check fails)
- maildev container works in gitlab CI when started as a sidecar (without environment variables)

I ended up removing maildev from the docker compose setup because realized that we do not need it (yet) for our e2e tests. The sidecar version without any environment variables still works and can be used with the unit tests.

I absolutely don't think this is related to maildev, really feels like there's some networking issue within the docker service itself. Good luck for further debugging!

**Comment by baseplusMB** [comment] 2024-03-22 14:38
Downgrade docker-ce to older release (25.0.5) fix the issue.

**Comment by Bessonov** [comment] 2024-03-22 16:45
Same issue. As a workaround I put following in the docker compose fine:

```yaml
    healthcheck:
      test: 'wget -O - http://127.0.0.1:$${MAILDEV_WEB_PORT}$${MAILDEV_BASE_PATHNAME}/healthz || exit 1'
```

**Comment by zguig52** [comment] 2024-03-23 10:05
Got same issue, seems more a recent bugfix in docker that starts to use the planned default healthcheck configured in the image.

Healthcheck configured doesn't work and docker does it job:
```
docker compose exec -it maildev wget -q http://127.0.0.1/healthz
wget: can't open 'healthz': File exists
```

I couldn't find any wget call that returns 200 code after beeing called a second time (always says this strange error can't open ...).

My fix was to force disabling healthcheck like this:
```
    healthcheck:
      disable: true
```

**Comment by zguig52** [comment] 2024-03-23 10:06
Root cause is tracked here: https://github.com/maildev/maildev/issues/474

**Comment by Nikola-Milovic** [comment] 2024-03-23 10:44
@zguig52 I think my specific issue is different from the one you mentioned, mine seems to be related to docker itself and some update in `v26.0` (since for me more than maildev and healthcheck are affected). But I am leaving the issue open since others seem to have similar issues

**Comment by zguig52** [comment] 2024-03-23 10:58
@Nikola-Milovic , got this also when upgrading Rocky 9 to latest docker:
```
docker --version
Docker version 26.0.0, build 2ae903e
```

I got other issues with curl/wget localhost configured healthchecks. I had to replace localhost with 127.0.0.1. Other communications are based on self defined extra_hosts.

Seems there is also something with DNS resolution in this version.

**Comment by zguig52** [comment] 2024-03-23 11:06
Could be related to this issue: https://github.com/moby/moby/issues/47414

I had also some weird transient behavior recently even before this upgrade with v25 where sometimes my containers where unable to communicate between them after restart and I had to destruct them to restart them (multiple networks attached with self configured IPs through IPAM module). I saw that they did not had all networks instantiated thus not listening on expected IPs.

**Comment by cowclaw** [comment] 2024-03-26 09:36
I can confirm that it does not work with `Docker version 26.0.0, build 2ae903e`. It works with `Docker version 25.0.5, build 5dc9bcc`. 

The root cause is that the wget (for healthcheck) tries ipv6 to connect. 

From within the maildev container:
```
~ $ wget http://localhost:1080/
Connecting to localhost:1080 ([::1]:1080)
wget: can't connect to remote host: Connection refused

~ $ wget http://127.0.0.1:1080/
Connecting to 127.0.0.1:1080 (127.0.0.1:1080)
saving to 'index.html'
index.html           100% |*************************************************************************************************************************************************************************************************************************************************************|  8390  0:00:00 ETA
'index.html' saved
```

Once can confirm that using telnet (after installing it):
```
telnet -6 localhost 1080
Trying ::1...
telnet: Unable to connect to remote host: Connection refused
```

**Comment by jehon** [comment] 2024-03-27 09:29
Same problem, and also related to localhost being translated as ipv6 instead of ipv4...

**Comment by clementmouchet** [comment] 2024-03-27 12:50
I've also defined my health check to support a self-signed certificate to run it over https:

```yaml
    healthcheck:
      test: wget --no-check-certificate --user-agent='Docker healthcheck' -O /dev/null https://localhost:1080/healthz || exit 1
      interval: 10s
      timeout: 1s
```

Not a big deal, but it might be worth adding it to the documentation?

**Comment by am97** [comment] 2024-04-04 16:33
This issue is also present on Docker 20.10.24+dfsg1 (Debian 12) when IPv6 is manually enabled. It's possible to reproduce it by placing the following lines in your `/etc/docker/daemon.json`, 

```json
{
    "ipv6": true,
    "fixed-cidr-v6": "fd00::/64"
}
```

Maildev currently listens on IPv4 only:

```
~ $ netstat -lptn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:1025            0.0.0.0:*               LISTEN      1/node
tcp        0      0 0.0.0.0:1080            0.0.0.0:*               LISTEN      1/node
```

Maybe it should listen on IPv6 too

**Comment by johnitvn** [comment] 2024-04-06 21:51
is this fixed on laster image?

**Comment by bakatz** [comment] 2024-06-13 08:53
For anyone struggling with this issue in GitHub Actions, the correct way to fix this until Docker gets their shit together is just to add this line in your actions yml in the container config:
`options: --health-cmd "wget -O /dev/null http://127.0.0.1:1080/healthz || exit 1" --health-interval 10s --health-timeout 5s --health-retries 5`

You may be able to use default interval/timeout/retries, haven't bothered testing.

Explanation: 
1. You need to use 127.0.0.1 instead of localhost because Docker is hosed and doesn't correctly resolve localhost -> 127.0.0.1 as of the latest version of docker, no idea why

2. Use http instead of https because the healthcheck endpoint doesn't have a valid cert associated with it and uses standard http, otherwise wget will throw. In my experience it will throw even if you pass --no-cert-check or whatever that option is so you need to force it to use http.

3. Send output to /dev/null (-O /dev/null) to avoid polluting the filesystem with the output of this endpoint

**Comment by cj-larsen** [comment] 2024-06-13 17:47
Another workaround that I used was setting the `MAILDEV_IP` to `::` as stated in #486 

Example: 
```
      # Mail Catcher
      maildev:
        image: maildev/maildev
        ports:
          - "1080:1080"
          - "1025:1025"
        env:
          MAILDEV_IP: "::"
```

**Comment by AndreasScharfCPB** [comment] 2024-08-09 08:31
Although the MAILDEV_IP: "::" did fix the health status of the container, maildev does not work anymore for me.
I get:
`MailDev webapp running at http://"::":1080/
node:events:492
      throw er; // Unhandled 'error' event
      ^
Error: getaddrinfo ENOTFOUND "::"
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:108:26)
Emitted 'error' event on Server instance at:
    at GetAddrInfoReqWrap.doListen [as callback] (node:net:1945:12)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:108:17) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: '"::"'
}`

**Comment by bakatz** [comment] 2024-08-10 05:19
> Although the MAILDEV_IP: "::" did fix the health status of the container, maildev does not work anymore for me. I get: `MailDev webapp running at http://"::":1080/ node:events:492 throw er; // Unhandled 'error' event ^ Error: getaddrinfo ENOTFOUND "::" at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:108:26) Emitted 'error' event on Server instance at: at GetAddrInfoReqWrap.doListen [as callback] (node:net:1945:12) at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:108:17) { errno: -3008, code: 'ENOTFOUND', syscall: 'getaddrinfo', hostname: '"::"' }`
> 
> What worked for me is disabling the health check: ` healthcheck: disable: true`
> 
> Now also my traefik picks it up again and the routing works

Seems like a weird issue, it still works for me in local dev using plain Docker. Did you try my alt solution involving using wget as the healthcheck to override whatever is there?

**Comment by am97** [comment] 2024-09-09 09:39
> Although the MAILDEV_IP: "::" did fix the health status of the container, maildev does not work anymore for me. I get: `MailDev webapp running at http://"::":1080/ node:events:492 throw er; // Unhandled 'error' event ^ Error: getaddrinfo ENOTFOUND "::" at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:108:26) Emitted 'error' event on Server instance at: at GetAddrInfoReqWrap.doListen [as callback] (node:net:1945:12) at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:108:17) { errno: -3008, code: 'ENOTFOUND', syscall: 'getaddrinfo', hostname: '"::"' }`
> 
> What worked for me is disabling the health check: ` healthcheck: disable: true`
> 
> Now also my traefik picks it up again and the routing works

It seems that your `MAILDEV_IP` variable has quotes in it's value. The value should be just `::`, not `"::"`. How do you declare the variable ?

**Comment by COil** [comment] 2024-09-10 18:11
Using `0.0.0.0` as the IP seems to work :

    healthcheck:
      test: ["CMD-SHELL", "wget -O - http://0.0.0.0:1080/healthz || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5

**Comment by rbwsam** [comment] 2024-09-15 07:04
I made a PR for a very simple fix and am using it now with Docker Compose. 

https://github.com/maildev/maildev/pull/500

See the commit message for the cause.

**Closed** 2024-12-08 00:31 UTC

**Comment by nul0op** [comment] 2026-08-21 08:55
> Another workaround that I used was setting the `MAILDEV_IP` to `::` as stated in [#486](https://github.com/maildev/maildev/pull/486)
> 
> Example:
> 
> ```
>       # Mail Catcher
>       maildev:
>         image: maildev/maildev
>         ports:
>           - "1080:1080"
>           - "1025:1025"
>         env:
>           MAILDEV_IP: "::"
> ```

maildev-1  | Error: Uncaught exception: getaddrinfo EAI_AGAIN "::"

so, it's not making it for me
